apiVersion: v2
name: kserve
description: A Helm chart to refer the official "kserve" helm chart
type: application
version: v0.14.1
dependencies:
  - name: kserve
    version: v0.14.1
    repository: oci://ghcr.io/kserve/charts
