victoriametrics:
  victoriametrics:
    server:
      service:
        type: LoadBalancer
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
    retention:
      period: "1"
    extraArgs:
      envflag.enable: "true"
      envflag.prefix: VM_
      loggerFormat: json
